In [8]:
import numpy as np
import pandas as pd
import scipy.stats as stats

In [22]:
data=pd.read_csv('/content/Students_Performance.csv')

In [21]:
data

,Month,Region,Manager,Sales_before_digital_add(in $),Sales_After_digital_add(in $)
0,Month-1,Region - A,Manager - A,132921,270390
1,Month-2,Region - A,Manager - C,149559,223334
2,Month-3,Region - B,Manager - A,146278,244243
3,Month-4,Region - B,Manager - B,152167,231808
4,Month-5,Region - C,Manager - B,159525,258402
5,Month-6,Region - A,Manager - B,137163,256948
6,Month-7,Region - C,Manager - C,130625,222106
7,Month-8,Region - A,Manager - A,131140,230637
8,Month-9,Region - B,Manager - C,171259,226261
9,Month-10,Region - C,Manager - B,141956,193735
10,Month-11,Region - B,Manager - C,159339,203175
11,Month-12,Region - A,Manager - A,178939,276279
12,Month-13,Region - B,Manager - A,145062,205180
13,Month-14,Region - A,Manager - A,151514,253131
14,Month-15,Region - C,Manager - A,147463,229336
15,Month-16,Region - A,Manager - B,177195,187305
16,Month-17,Region - A,Manager - C,140862,234908
17,Month-18,Region - C,Manager - B,167996,191517
18,Month-19,Region - B,Manager - A,132135,227040
19,Month-20,Region - A,Manager - B,152493,212579
20,Month-21,Region - B,Manager - A,147425,263388
21,Month-22,Region - A,Manager - C,130263,243020

a. Find out how many males and females participated in
the test.

In [23]:
df = pd.DataFrame(data)
print(df['gender'].value_counts())

female    518
male      482
Name: gender, dtype: int64

b. What do you think about the students' parental level of
education?

The data shows parents of all students are educated. But a few possess Masters Degree.

In [24]:
df['parental level of education'].value_counts()

some college          226
associate's degree    222
high school           196
some high school      179
bachelor's degree     118
master's degree        59
Name: parental level of education, dtype: int64

c. Who scores the most on average for math, reading and
writing based on
i. Gender
ii. Test preparation course

In [25]:
df.groupby(['gender','test preparation course'])['math score','reading score','writing score'].mean()

<ipython-input-25-fff1c34360df>:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  df.groupby(['gender','test preparation course'])['math score','reading score','writing score'].mean()

                                math score  reading score  writing score
gender test preparation course
female completed                 67.108696      77.375000      78.793478
       none                      61.320359      69.955090      68.982036
male   completed                 72.988506      70.793103      70.339080
       none                      66.467532      62.581169      59.551948

d. What do you think about the scoring variation for
math, reading and writing based on
i. Gender
ii. Test preparation course

In [26]:
df.groupby(['gender','test preparation course'])['math score','reading score','writing score'].std()

<ipython-input-26-52ece2734e79>:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  df.groupby(['gender','test preparation course'])['math score','reading score','writing score'].std()

                                math score  reading score  writing score
gender test preparation course
female completed                 14.428233      12.695493      12.240788
       none                      16.510686      14.636981      15.016497
male   completed                 14.039164      13.612420      12.887910
       none                      14.335746      13.595718      13.468284

e. The management needs your help to give bonus points
to the top 25% of students based on their math score,
so how will you help the management to achieve this.

In [41]:
math_25th_percentile = np.percentile(df['math score'], 25)
math_25th_percentile
top_25_percent_students = data[data['math score'] >= 57.0]
bonus_points = 5
top_25_percent_students["bonus"] = bonus_points
top_25_percent_students.to_csv("students_with_bonus.csv", index=False)

<ipython-input-41-c0317f3d489b>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  top_25_percent_students["bonus"] = bonus_points

In [40]:
top_25_percent_students["bonus"] = bonus_points

top_25_percent_students.to_csv

<bound method NDFrame.to_csv of      gender race/ethnicity parental level of education         lunch  \
153  female        group B          associate's degree      standard
154  female        group B            some high school      standard
155  female        group C          associate's degree  free/reduced
156  female        group C          associate's degree      standard
157  female        group D          associate's degree  free/reduced
..      ...            ...                         ...           ...
995    male        group E                some college      standard
996    male        group A                some college      standard
997    male        group D                some college      standard
998    male        group E          associate's degree  free/reduced
999    male        group E           bachelor's degree      standard

    test preparation course  math score  reading score  writing score  bonus
153                    none          57             69             68      5
154                    none          57             67             72      5
155                    none          57             78             67      5
156               completed          57             77             80      5
157               completed          57             74             76      5
..                      ...         ...            ...            ...    ...
995               completed          99             87             81      5
996               completed         100             96             86      5
997               completed         100             97             99      5
998               completed         100            100             93      5
999               completed         100            100            100      5

[753 rows x 9 columns]>

**Case Study on Testing of Hypothesis**
2. A company started to invest in digital marketing as a new
way of their product promotions. For that they collected
data and decided to carry out a study on it

In [15]:
import numpy as np
from scipy import stats

In [16]:
data=pd.read_csv('/content/Sales_add.csv')

In [12]:
data

,Month,Region,Manager,Sales_before_digital_add(in $),Sales_After_digital_add(in $)
0,Month-1,Region - A,Manager - A,132921,270390
1,Month-2,Region - A,Manager - C,149559,223334
2,Month-3,Region - B,Manager - A,146278,244243
3,Month-4,Region - B,Manager - B,152167,231808
4,Month-5,Region - C,Manager - B,159525,258402
5,Month-6,Region - A,Manager - B,137163,256948
6,Month-7,Region - C,Manager - C,130625,222106
7,Month-8,Region - A,Manager - A,131140,230637
8,Month-9,Region - B,Manager - C,171259,226261
9,Month-10,Region - C,Manager - B,141956,193735
10,Month-11,Region - B,Manager - C,159339,203175
11,Month-12,Region - A,Manager - A,178939,276279
12,Month-13,Region - B,Manager - A,145062,205180
13,Month-14,Region - A,Manager - A,151514,253131
14,Month-15,Region - C,Manager - A,147463,229336
15,Month-16,Region - A,Manager - B,177195,187305
16,Month-17,Region - A,Manager - C,140862,234908
17,Month-18,Region - C,Manager - B,167996,191517
18,Month-19,Region - B,Manager - A,132135,227040
19,Month-20,Region - A,Manager - B,152493,212579
20,Month-21,Region - B,Manager - A,147425,263388
21,Month-22,Region - A,Manager - C,130263,243020

In [ ]:
Sales_before_digital_add   =  data['Sales_before_digital_add']
Sales_After_digital_add  =  data['Sales_After_digital_add']
t_val,p_val = stats.ttest_1samp(Sales_before_digital_add, Sales_After_digital_add)
aplha =0.05
if p_val<alpha:
  print("There is a significant increase in sales after implementing digital marketing.")
else:
    print("There is no significant increase in sales after implementing digital marketing.")